baseURL = 'https://www.fuentederecho.com.ar/'
languageCode = 'es-ar'
title = '§ Fuente de Derecho'

[menu]
  [[menu.main]]
    pageRef = "search"
    weight = -100
    [menu.main.params]
      type = "search"
  [[menu.main]]
    identifier = "Ley"
    name = "§ Ley"
    url = "/ley/"
    weight = 1
  [[menu.main]]
    identifier = "Jurisprudencia"
    name = "§ Jurisprudencia"
    url = "/jurisprudencia/"
    weight = 2
  [[menu.main]]
    identifier = "Doctrina"
    name = "§ Doctrina"
    url = "/doctrina/"
    weight = 3
  [[menu.main]]
    identifier = "Novedades"
    name = "§ Novedades"
    url = "/novedades/"
    weight = 4
  [[menu.main]]                               # Este seria un cambio a hacer  8/9/2025
    identifier = "Etiquetas"                  # Este seria un cambio a hacer  8/9/2025
    name = "Etiquetas"                        # Este seria un cambio a hacer  8/9/2025
    pageRef = "tags"                          # Este seria un cambio a hacer  8/9/2025  
    weight = 5                                # Este seria un cambio a hacer  8/9/2025

[params]
  description = "Tu descripción del sitio"

  [params.search]
    enable = true

[taxonomies]
  categoria = "categories"
  tag = "tags"
  author = "authors"

[module]
  [[module.imports]]
    path = "github.com/imfing/hextra"
