baseURL = 'https://www.fuentederecho.com.ar/'
languageCode = 'es-ar'
title = '§ Fuente de Derecho'

[menu]
  [[menu.main]]
    pageRef = "search"
    weight = -100
    [menu.main.params]
      type = "search"
  [[menu.main]]
    identifier = "Ley"
    name = "§ Ley"
    url = "/ley/"
    weight = 1
  [[menu.main]]
    identifier = "Jurisprudencia"
    name = "§ Jurisprudencia"
    url = "/jurisprudencia/"
    weight = 2
  [[menu.main]]
    identifier = "Doctrina"
    name = "§ Doctrina"
    url = "/doctrina/"
    weight = 3
  [[menu.main]]
    identifier = "Novedades"
    name = "§ Novedades"
    url = "/novedades/"
    weight = 4
 # [[menu.main]]
 #   identifier = "Etiquetas"
 #   name = "Etiquetas"
 #   pageRef = "tags"
 #   weight = 5
  [[menu.main]]             # Agregado por Tesauro en vez de etiquetas
    identifier = "Tesauro"  # Agregado por Tesauro en vez de etieuqtas
    name = "Tesauro"        # Agregado por Tesauro en vez de etiquetas
    url = "/tesauro/"       # Agregado por Tesauro en vez de etiquetas
    weight = 5              # Agregado por Tesauro en vez de etiquetas
 

[params]
  description = "Tu descripción del sitio"

  [params.search]
    enable = true

[taxonomies]
  categoria = "categories"
  tag = "tags"
  author = "authors"

 [module]
 [[module.imports]]
  path = "github.com/imfing/hextra"
